spring:
  profiles:
    active: local
    include: security

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: su

  h2:
    console:
      enabled: true

cors:
  allowed:
    api: /**
    method: '*'
    origin:
      - http://localhost:3000
      - http://localhost:8080
