security:
  patterns:
    ignoring:
      ALL:
        - /static/**
        - /favicon.ico
        - /h2-console/**
        - /api/**/auth/**
        - /api/**/users
    permit-all:
      ALL:
        - /
      GET: [ ]
      POST: [ ]
jwt:
  issuer: gagebu
  secret-key: ${JWT_SECRET_KEY}
  access-token:
    expire-length: 1_800_000 # 30분
