version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-gagebu
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=gagebu
      - MYSQL_USER=su
      - MYSQL_PASSWORD=gagebu
      - MYSQL_DATABASE=gagebu
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  gagebu:
    image: kimziou77/gagebu
    container_name: gagebu
    ports:
      - "80:8080"
    environment:
      PROFILE: prod
      DB_URL: jdbc:mysql://mysql-gagebu:3306/gagebu
      DB_PASSWORD: gagebu
    restart: always
    depends_on:
      - mysql
