version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=gagebu
      - MYSQL_USER=su
      - MYSQL_PASSWORD=gagebu
      - MYSQL_DATABASE=gagebu
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  gagebu:
    image: kimziou77/gagebu
    container_name: gagebu
    ports:
      - "80:8080"
    environment:
      PROFILE: prod
      SEVER_NAME: http://34.125.126.248
      JWT_SECRET_KEY: 6rmA7IiY67mI7J2Y6rCA6rOE67aA7ZSE66Gc6re4656o
      DB_URL: jdbc:mysql://mysql:3306/gagebu
      DB_PASSWORD: gagebu
    restart: always
    depends_on:
      - mysql
